name: CI-CD to GKE

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: project-dd80ba5b-11fc-4806-a35
  REGION: asia-south1
  CLUSTER_NAME: flask-gke-cluster
  IMAGE_NAME: flask-ci-app
  REPO_NAME: flask-repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/651575538350/locations/global/workloadIdentityPools/github-pool/providers/github-provider
        service_account: github-ci@project-dd80ba5b-11fc-4806-a35.iam.gserviceaccount.com

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

    - name: Build & Push Docker Image
      run: |
        docker build -t asia-south1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$GITHUB_SHA .
        docker push asia-south1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$GITHUB_SHA

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials $CLUSTER_NAME --region $REGION --project $PROJECT_ID

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/
        kubectl set image deployment/flask-app flask=asia-south1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$GITHUB_SHA
